kind: pipeline
name: build
steps:
- name: publish-image  
  image: plugins/docker
  settings:
    username: "debianmaster"
    password:
      from_secret: docker_password
    repo: docker.io/debianmaster/helloworldapp
    registry: docker.io
    dockerfile: ./Dockerfile
    tags:
      - master
      - "${DRONE_TAG}"
  when:
    event: [tag,push]
    status: success
    branch:
      - master
      - refs/tags/*