kind: pipeline
name: build

clone:
  depth: 1

steps:
- name: publish-image  
  image: plugins/docker
  settings:
    username: "debianmaster"
    password:
      from_secret: docker_password
    repo: docker.io/debianmaster/helloworldapp
    registry: docker.io
    dockerfile: ./Dockerfile
    tags: 
    - ${DRONE_BRANCH/feature\//}
  when: 
    ref: [ refs/heads/feature/*, refs/tags/* ]
    event: [ push, tag ]

- name: promote  
  image: plugins/docker
  settings:
    username: "debianmaster"
    password:
      from_secret: docker_password
    repo: docker.io/debianmaster/helloworldapp
    registry: docker.io
    dockerfile: ./Dockerfile
    tags: 
    - ${DRONE_TAG}
  when: 
    event: deployment
    environment: production