---
global-variables:
  environment: &default_environment
    test_secret:
      from_secret: test_secret

kind: pipeline
name: build
clone:
  depth: 1
steps:
- name: debug
  image: biqmind/k8s-cli
  environment:
    <<: *default_environment
  settings:
    test_secret2:
      from_secret: test_secret
  commands:
    - >
      echo $$test_secret > test.yaml
      cat test.yaml
      echo $$test_secret2
      echo ${test_secret}
      echo $${test_secret}

- name: publish-image  
  image: plugins/docker
  settings:
    username: "debianmaster"
    password:
      from_secret: docker_password
    repo: docker.io/debianmaster/helloworldapp
    registry: docker.io
    dockerfile: ./Dockerfile
    tags: 
    - ${DRONE_BRANCH/feature\//}
  when: 
    ref: [ refs/heads/feature/*, refs/tags/* ]
    event: [ push, tag ]

- name: promote  
  image: plugins/docker
  settings:
    username: "debianmaster"
    password:
      from_secret: docker_password
    repo: docker.io/debianmaster/helloworldapp
    registry: docker.io
    dockerfile: ./Dockerfile
    tags: 
    - production
  when: 
    event: promote
    environment: production