kind: pipeline
name: build

clone:
  depth: 1

steps:
- name: publish-image  
  image: plugins/docker
  settings:
    username: "debianmaster"
    password:
      from_secret: docker_password
    repo: docker.io/debianmaster/helloworldapp
    registry: docker.io
    dockerfile: ./Dockerfile
    auto_tag: true
  trigger: 
    branch:
      - master
      - feature/*
    event:
    - pull_request
    - tag
    - promote