
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: helloworld
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      run: helloworld
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: helloworld
    spec:
      containers:
      - image: biqmind/helloworld
        name: helloworld
        ports:
        - containerPort: 80
        resources: {}
status: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hw-ingress
spec:
  rules:
  - host: hw.harsh.stg.cape.sh
    http:
      paths:
      - backend:
          serviceName: helloworld
          servicePort: 80
