apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: helloworld
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: helloworld
status:
  loadBalancer: {}
